---
title: "READ_ME"
author: "Luke Keevers"
date: '2022-10-12'
output: html_document
---
The following custom scripts were used to analyse the data for an experiment conducted by Luke Keevers in the completion of his Honours thesis. Apologies in advance for the messiness of the scripts. They were not written with reproducibility in mind, although hopefully anyone curious can understand the gist of the analyses conducted. See Appendix B in the submitted thesis for full edited statistical output, which also should be sufficient to understand all statistical procedures used.

So-called 'Wrangle' scripts are those used to prepare the raw data from MedPC for analysis. As such, these scripts produced the data submitted for review. 

The 'Analysis' scripts contain the relevant code used for final analyses. They are messy and contain legacy code no longer used in the final analyses, but still should convey the main statistical tests used. 

If you have come this far and would like to know more information about the current scripts, please do not hesitate to reach out to me at lukekeevers@gmail.com

